spring:
  data:
    mongodb:
      username: felipeadmin
      password: root@1234
      host: localhost
      port: 27017
      database: customerdb
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.felipesantos.ecommerce.kafka.OrderConfirmationRequest,paymentConfirmation:com.felipesantos.ecommerce.kafka.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: felipeadmin
    password: root@1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

kafka:
  topic:
    payment-topic: payment-topic
    order-topic: order-topic

server:
  port: 8040