spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: felipeadmin
    password: root@1234

    jpa:
      hibernate:
        ddl-auto: validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8070

app-config:
  services:
    ms-customer:
      url: http://localhost:8222/api/v1/customers
    ms-payment:
      url: http://localhost:8222/api/v1/payments
    ms-product:
      url: http://localhost:8222/api/v1/products

  logging:
    level:
      org:
        springframework:
          jdbc: DEBUG
        hibernate:
          SQL: DEBUG