spring:
  application:
    name: discovery-service

  config:
    import: optional:configserver:http://localhost:8888  # if not find the configuration of ther ms, it will run in 8080 port

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/

server:
  port: 8761