CREATE SEQUENCE IF NOT EXISTS SEQ_CATEGORY START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INTEGER NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_PRODUCT START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PRODUCT (
     ID INTEGER NOT NULL PRIMARY KEY,
     DESCRIPTION VARCHAR(255),
     NAME VARCHAR(255),
     AVAILABLE_QUANTITY DOUBLE PRECISION NOT NULL,
     PRICE NUMERIC(38, 2),
     CATEGORY_ID INTEGER
);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY;